cleanAWS: &cleanAWS
    machine: true
    steps:
    - checkout

    - attach_workspace:
        at: .

    - run: ./scripts/aws_credentials.sh ${TYPE}

    - run: ./ci-cleaner aws --access-key-id ${AWS_ACCESS_KEY_ID} --secret-access-key ${AWS_SECRET_ACCESS_KEY} --region ${AWS_DEFAULT_REGION}



cleanAzure: &cleanAzure
    machine: true
    steps:
    - checkout

    - attach_workspace:
        at: .

    - run: ./ci-cleaner azure --client-id ${AZURE_CLIENT_ID} --client-secret ${AZURE_CLIENT_SECRET} --tenant-id ${AZURE_TENANT_ID} --subscription-id ${AZURE_SUBSCRIPTION_ID} --location ${AZURE_LOCATION}



version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout

    - run: |
        wget -q $(curl -sS https://api.github.com/repos/giantswarm/architect/releases/latest | grep browser_download_url | head -n 1 | cut -d '"' -f 4)
        chmod +x ./architect
        ./architect version

    - run: ./architect build

    - persist_to_workspace:
        root: .
        paths:
        - ./ci-cleaner

  cleanAWSHost:
    environment:
      TYPE: "host"
    <<: *cleanAWS

  cleanAWSGuest:
    environment:
      TYPE: "guest"
    <<: *cleanAWS

  cleanAzure:
    <<: *cleanAzure



workflows:
  version: 2

  build:
    jobs:
    - build

  cleanup:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only: master

    jobs:
    - build
    - cleanAWSGuest:
        requires:
        - build
    - cleanAWSHost:
        requires:
        - build
    - cleanAzure:
        requires:
        - build
